# Generated by Django 3.2.8 on 2021-10-31 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('codeId', models.IntegerField(primary_key=True, serialize=False)),
                ('timeOfCreation', models.DateTimeField()),
                ('value', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.AddField(
            model_name='reservation',
            name='email',
            field=models.EmailField(default='test@test.test', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='fullName',
            field=models.CharField(default='John Doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='phone',
            field=models.CharField(default='123456789', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservationID',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default='Confirmed', max_length=60),
        ),
        migrations.AddField(
            model_name='reservation',
            name='verificationCode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.verificationcode'),
        ),
    ]
